allowBuilds:
  '@parcel/watcher': true
  cwebp-bin: true
  es5-ext: true
  gifsicle: true
  guetzli: true
  husky: true
  jpeg-recompress-bin: true
  mozjpeg: true
  optipng-bin: true
  pngquant-bin: true
  swiper: true
  zopflipng-bin: true
